### ISSUE TITLE
Missing function : FreeDiskSpace

### ISSUE THREAD

**Issue by Imaginos** [inode64/WindowsClearCache#2]
Great script, I love it !
Allthough, a function is called twice but not defined : FreeDiskSpace
Here's how I added it (rounding with 2 digit) : 
Function FreeDiskSpace{
	param([string]$Diskletter)
	return ([math]::Round((Get-Volume -DriveLetter $Diskletter | select @{Name="GB";Expression={$_.SizeRemaining/1GB}}).GB, 2))
}

In my script, I prefered to get the result in MB : 
Function FreeDiskSpace{
	param([string]$Diskletter)
	return ([math]::Round((Get-Volume -DriveLetter $Diskletter | select @{Name="MB";Expression={$_.SizeRemaining/1MB}}).MB, 2))
}

I call it through "FreeDiskSpace 'C'"

**Comment by inode64** [comment]
Thanks for your help.
I have already added the function in commit eaf380a

Any suggestion and help will be welcome

**Comment by inode64** [comment]
Solved, we close task
